spring:
  jackson:
    serialization: {indent-output: true}
  sleuth:
    sampler: {probability: 1}
  mail: {port: 25, host: localhost}
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery: {enabled: true}
    enabled: false
  couchbase:
    bucket: {password: password, name: Employee}
    bootstrap-hosts: couchbase.smartmeter
  profiles:
    include: [swagger]
    active: dev
  messages: {cache-duration: PT1S}
  jpa:
    properties: {hibernate.cache.hazelcast.instance_name: billingservice}
  devtools:
    livereload: {enabled: false}
    restart: {enabled: true}
  thymeleaf: {cache: false}
server: {port: 8080}
jhipster:
  cache:
    hazelcast:
      management-center: {update-interval: 3, enabled: false, url: 'http://localhost:8180/mancenter'}
      time-to-live-seconds: 3600
      backup-count: 1
  security:
    authentication:
      jwt: {base64-secret: ZDFkNjE4ZWFlNmUzMzQwODFiYzYzODFlZDJjMWJiMjJmMDhiOGM3NzljMTUzZmNmOGQ2MWQwZGZjMWQ1Yjc0YmRhZTAyODUxYTU3ZjUzNGZjMWYyZjRhYzNjZGQ2ZjhkMGNlZjJmMDhhZjYzNWZkMDZjNzg2YzliMDEyNGRhZTU=,
        token-validity-in-seconds: 86400, token-validity-in-seconds-for-remember-me: 2592000}
  mail: {base-url: 'http://127.0.0.1:8080', from: billingservice@localhost}
  http: {version: V_1_1}
  logging:
    logstash: {port: 5000, queue-size: 512, host: localhost, enabled: false}
  metrics:
    logs: {report-frequency: 60, enabled: false}
management:
  endpoint:
    prometheus: {enabled: 'true'}
logging:
  level: {ROOT: DEBUG, io.github.jhipster: DEBUG, pom.infy.test: DEBUG}
