version: '2'
services:
    billingservice-app:
        image: billingservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=billingservice-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=billingservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    billingservice-couchbase:
        extends:
            file: couchbase.yml
            service: billingservice-couchbase
